version: '3'

services:
  avisonav-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    volumes:
      - apistorage:/var/www/html/storage
    networks:
      - app-network

  web:
    restart: always
    links:
      - avisonav-api
    ports:
      - "80:80"
    working_dir: /var/www
    volumes:
      - ./docker/prod/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/prod/nginx/log/:/var/log/nginx/
      - apistorage:/var/www:ro
    networks:
      - app-network

volumes:
  dbdata:
    driver: local
  apistorage:
    driver: local

networks:
  app-network:
    driver: bridge