version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/dev/php/Dockerfile
    image: avisonav-api-dev
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/dev/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    env_file: .env
    links:
      - db

  web:
    restart: unless-stopped
    links:
      - api
    volumes:
      - ./:/var/www
      - ./docker/dev/nginx/conf.d:/etc/nginx/conf.d/
      - ./docker/dev/nginx/log:/var/log/nginx/
    ports:
      - "8081:80"

  db:
    image: mysql:8.0.16
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prueba
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
#      - ./docker/dev/mysql/my.cnf:/etc/mysql/my.cnf

volumes:
  dbdata:
    driver: local