version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file: .env
    volumes:
      - apistorage:/var/www/html/storage

  web:
    restart: always
    links:
      - api
    working_dir: /var/www
    volumes:
      - ./docker/prod/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/prod/nginx/log/:/var/log/nginx/
      - apistorage:/var/www:ro
    ports:
      - 8088:80

volumes:
  apistorage:
    driver: local